"""empty message

Revision ID: 606c2c92ec0f
Revises: 6ba4de759bb5
Create Date: 2023-04-24 18:19:55.703763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606c2c92ec0f'
down_revision = '6ba4de759bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
