"""empty message

Revision ID: 6ba4de759bb5
Revises: 818019d7b0bd
Create Date: 2023-04-24 17:52:33.704385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba4de759bb5'
down_revision = '818019d7b0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))

    # ### end Alembic commands ###
